### ISSUE TITLE
ps computer: PyCMDS doesn't start due to Slack error. Turning off bots via ini file allows startup to happen.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#182] opened 2018-09-06 23:52 UTC
```
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DFB0C60>), ('Ba
se', <project.classes.Filepath object at 0x0DFB0F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0DFC1030>)])
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DFB0C60>), ('Ba
se', <project.classes.Filepath object at 0x0DFB0F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0DFC1030>)])
w1  dequeue: initialize [(), {}] True
HEIIDSLKDFJLKJASLK,  [(5, 6)]
[5, 6]
<hardware.opas.PoyntingCorrection.ZaberCorrectionDevice.ZaberCorrectionDevice ob
ject at 0x0E38CE90> wn
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0E38EBC0>), ('Cu
rve', <project.classes.Filepath object at 0x0E38EC10>)])
w2  dequeue: initialize [(), {}] True
HEIIDSLKDFJLKJASLK,  [(3, 4)]
[3, 4]
<hardware.opas.PoyntingCorrection.ZaberCorrectionDevice.ZaberCorrectionDevice ob
ject at 0x0E393670> wn
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0E3B9670>), ('Cu
rve', <project.classes.Filepath object at 0x0E3B96C0>)])
w3  dequeue: initialize [(), {}] True
wm  dequeue: initialize [(), {}] True
None _open_device b'C:\\Users\\John\\source\\PyCMDS\\hardware\\opas\\TOPAS\\conf
iguration\\16426.ini'
d1  dequeue: initialize [(), {}] True
d2  dequeue: initialize [(), {}] True
[5, 6]
[3, 4]
<class 'PCI-6251.Driver'> OrderedDict() <class 'PCI-6251.GUI'> NI PCI-6251 None
DEVICE INIT
UPDATE SAMPLE CORRESPONDANCES
['signal', 'pyro1', 'pyro2', 'pyro3', 'PMT voltage', 'w1 chopper', 'w2 chopper']

Virtual  dequeue: initialize [(), {}] True
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
[1, 2]
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DFB0C60>), ('Ba
se', <project.classes.Filepath object at 0x0DFB0F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0DFC1030>)])
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DFB0C60>), ('Ba
se', <project.classes.Filepath object at 0x0DFB0F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0DFC1030>)])
['channel_0', 'channel_1', 'channel_2', 'channel_3', 'channel_4']
Virtual  dequeue: loop [(), {}] True
DEVICE CONTROL INITIALIZE COMPLETE ['channel_0', 'channel_1', 'channel_2', 'chan
nel_3', 'channel_4']
Virtual exiting loop!
initialize widgets
Virtual  dequeue: loop [(), {}] True
Virtual exiting loop!
Virtual  dequeue: loop [(), {}] True
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: Runti
meWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWar
ning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
['w3']
['w3']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
channel names ['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_no
rm', 'pyro1', 'pyro2', 'pyro3', 'PMT voltage']
load modules
<configparser.SafeConfigParser object at 0x195B2790> C:\Users\John\source\PyCMDS
\somatic\order\order.ini
Virtual exiting loop!
Virtual  dequeue: loop [(), {}] False
Virtual exiting loop!
Virtual  dequeue: loop [(), {}] False
['w1', 'w2', 'w3']
MOTORTUNE w1 ['Crystal', 'Amplifier', 'Grating', 'NDFG_Crystal', 'NDFG_Mirror',
'NDFG_Delay', 'Phi', 'Theta']
MOTORTUNE w2 ['Grating', 'BBO', 'Mixer', 'Phi', 'Theta']
MOTORTUNE w3 ['Grating', 'BBO', 'Mixer', 'Phi', 'Theta']
<class 'hardware.opas.opas.Hardware'>
<class 'hardware.opas.opas.Hardware'>
<class 'hardware.opas.opas.Hardware'>
['SCAN', 'TUNE TEST', 'AUTOTUNE', 'MOTORTUNE', 'POYNTING TUNE']
PyCMDS_ui.MainWindow.__init__ complete
None _open_device b'C:\\Users\\John\\source\\PyCMDS\\hardware\\opas\\TOPAS\\conf
iguration\\16426.ini'
TOPAS is busy 0 True
w2 Grating
w2 Grating
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
w3 Grating
w3 Grating
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
w1 Crystal
w1 Crystal
['signal preamp', 'signal poweramp', 'SHS']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
['signal_diff', 'signal_diff_norm', 'signal_mean', 'signal_mean_norm', 'pyro1',
'pyro2', 'pyro3', 'PMT voltage']
shutdown
w1  dequeue: save_status [(), {}] True
w1  dequeue: close [(), {}] True
w1  dequeue: check_busy [(), {}] True
w2  dequeue: save_status [(), {}] True
w2  dequeue: close [(), {}] True
w2  dequeue: check_busy [(), {}] True
w3  dequeue: save_status [(), {}] True
w3  dequeue: close [(), {}] True
w3  dequeue: check_busy [(), {}] True
wm  dequeue: save_status [(), {}] True
wm  dequeue: close [(), {}] True
wm  dequeue: check_busy [(), {}] True
d1  dequeue: save_status [(), {}] True
c:\users\john\source\wrighttools\WrightTools\units.py:114: UserWarning: conversi
on None to mm not valid: returning input
  current_unit, destination_unit))
d1  dequeue: close [(), {}] True
d1  dequeue: check_busy [(), {}] True
d2  dequeue: save_status [(), {}] True
d2  dequeue: close [(), {}] True
d2  dequeue: check_busy [(), {}] True
drive  dequeue: close [(), {}] True
Traceback (most recent call last):
  File "C:\Users\John\source\PyCMDS\project\google_drive\google_drive.py", line
91, in dequeue
    getattr(self, method)(*args, **kwargs)
AttributeError: 'Address' object has no attribute 'close'
w1 Crystal
w1 Crystal
w1 Crystal
w1 Crystal
w1 Crystal
w2 Grating
w2 Grating
w2 Grating
w2 Grating
w2 Grating
w3 Grating
w3 Grating
w3 Grating
w3 Grating
w3 Grating
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
Win32 exception occurred releasing IUnknown at 0x0fe58524
QThread: Destroyed while thread is still running

(base) C:\Users\John\source\PyCMDS>python pycmds.py
C:\Users\John\Miniconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: C
onversion of the second argument of issubdtype from `float` to `np.floating` is
deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type
`.
  from ._conv import register_converters as _register_converters
initialize hardware
HEIIDSLKDFJLKJASLK,  [(1, 2)]
[1, 2]
<hardware.opas.PoyntingCorrection.ZaberCorrectionDevice.ZaberCorrectionDevice ob
ject at 0x0DF58350> wn
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DF50C60>), ('Ba
se', <project.classes.Filepath object at 0x0DF50F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0E05C030>)])
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DF50C60>), ('Ba
se', <project.classes.Filepath object at 0x0DF50F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0E05C030>)])
w1  dequeue: initialize [(), {}] True
HEIIDSLKDFJLKJASLK,  [(5, 6)]
[5, 6]
<hardware.opas.PoyntingCorrection.ZaberCorrectionDevice.ZaberCorrectionDevice ob
ject at 0x0E08B670> wn
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0E08EBC0>), ('Cu
rve', <project.classes.Filepath object at 0x0E08EC10>)])
w2  dequeue: initialize [(), {}] True
HEIIDSLKDFJLKJASLK,  [(3, 4)]
[3, 4]
<hardware.opas.PoyntingCorrection.ZaberCorrectionDevice.ZaberCorrectionDevice ob
ject at 0x0E08BF70> wn
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0E0BA670>), ('Cu
rve', <project.classes.Filepath object at 0x0E0BA6C0>)])
w3  dequeue: initialize [(), {}] True
wm  dequeue: initialize [(), {}] True
None _open_device b'C:\\Users\\John\\source\\PyCMDS\\hardware\\opas\\TOPAS\\conf
iguration\\16426.ini'
d1  dequeue: initialize [(), {}] True
d2  dequeue: initialize [(), {}] True
[5, 6]
[3, 4]
<class 'PCI-6251.Driver'> OrderedDict() <class 'PCI-6251.GUI'> NI PCI-6251 None
DEVICE INIT
UPDATE SAMPLE CORRESPONDANCES
['signal', 'pyro1', 'pyro2', 'pyro3', 'PMT voltage', 'w1 chopper', 'w2 chopper']

Virtual  dequeue: initialize [(), {}] True
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
QWidget::setLayout: Attempting to set QLayout "" on ExpandingWidget "", which al
ready has a layout
['channel_0', 'channel_1', 'channel_2', 'channel_3', 'channel_4']
Virtual  dequeue: loop [(), {}] True
Virtual exiting loop!
Virtual  dequeue: loop [(), {}] True
Virtual exiting loop!
DEVICE CONTROL INITIALIZE COMPLETE ['channel_0', 'channel_1', 'channel_2', 'chan
nel_3', 'channel_4']
Virtual  dequeue: loop [(), {}] True
initialize widgets
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: Runti
meWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWar
ning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
['w3']
['w3']
[1, 2]
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DF50C60>), ('Ba
se', <project.classes.Filepath object at 0x0DF50F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0E05C030>)])
OrderedDict([('Poynting', <project.classes.Filepath object at 0x0DF50C60>), ('Ba
se', <project.classes.Filepath object at 0x0DF50F80>), ('Mixer 3', <project.clas
ses.Filepath object at 0x0E05C030>)])
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: Runti
meWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\John\Miniconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWar
ning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
None _open_device b'C:\\Users\\John\\source\\PyCMDS\\hardware\\opas\\TOPAS\\conf
iguration\\16426.ini'
TOPAS is busy 0 True
Traceback (most recent call last):
  File "C:\Users\John\Miniconda3\lib\site-packages\slackclient\client.py", line
52, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "C:\Users\John\Miniconda3\lib\site-packages\slackclient\server.py", line
85, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
Traceback (most recent call last):
  File "pycmds.py", line 302, in <module>
    main_form = main()
  File "pycmds.py", line 296, in main
    MainWindow = MainWindow()
  File "pycmds.py", line 114, in __init__
    self._load_witch()
  File "pycmds.py", line 264, in _load_witch
    import project.slack as slack
  File "C:\Users\John\source\PyCMDS\project\slack\__init__.py", line 1, in <modu
le>
    from . import slack
  File "C:\Users\John\source\PyCMDS\project\slack\slack.py", line 16, in <module
>
    from . import bots
  File "C:\Users\John\source\PyCMDS\project\slack\bots.py", line 166, in <module
>
    witch = PyCMDS_bot(witch_token)
  File "C:\Users\John\source\PyCMDS\project\slack\bots.py", line 46, in __init__

    hello = self.rtmbot.rtm_read()
  File "C:\Users\John\source\PyCMDS\project\slack\rtmbot.py", line 54, in rtm_re
ad
    return self.slack_client.rtm_read()
  File "C:\Users\John\Miniconda3\lib\site-packages\slackclient\client.py", line
135, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "C:\Users\John\Miniconda3\lib\site-packages\slackclient\server.py", line
194, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
AttributeError: 'NoneType' object has no attribute 'recv'
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
```

**Comment by ksunden** [comment] 2018-09-10 15:56
Cannot reproduce. A weekend of sitting and doing nothing seems to have fixed the error.
Perhaps networking was disconnected briefly?
Cannot really say, at this point, it's keep an eye on it see if it happens again, but closing as no problem persists.

**Closed by ksunden** 2018-09-10 15:56 UTC
