### ISSUE TITLE
When scanning monochromator "Conversion None to nm not valid: returning input"

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#113] opened 2017-07-06 15:20 UTC
When scanning monochromator, after each step, four `conversion None to nm not valid: returning input` are printed to the command line. 

This behavior does not seem to be present when merely setting the monochromator from the main console.

**Comment by ksunden** [comment] 2017-08-10 15:34
Is this causing any real effect, or is the only symptom the statement on the log?

This could be caused by a system that is working in the native units, but does not attach the units to the number, and thus the conversion is unnecessary. 

Regardless, this should be fixed, but if it is purely cosmetic, may wait for scopy

**Comment by untzag** [comment] 2017-08-10 18:26
It is cosmetic. Leave it be for now, I might remember to fix if I'm inside the mono code for some other reason.

**Closed** 2018-03-20 15:16 UTC
Labels: bug, wont fix
