### ISSUE TITLE
Act of requesting status from Slack appears to have frozen PyCMDS

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#171] opened 2018-04-26 23:46 UTC
I asked slack for PyCMDS's status and it appears to have stopped the scan and completely frozen up PyCMDS.

![slack_crash](https://user-images.githubusercontent.com/13207251/39337348-131440c4-4982-11e8-9561-c26548445a55.PNG)

**Comment by ksunden** [comment] 2018-05-16 20:18
Closing because this is not reproducible.

I do not believe it was asking slack which caused it to freeze, but rather something else, as Witch continued to respond.

**Closed by ksunden** 2018-05-16 20:18 UTC
