### ISSUE TITLE
In soft shutdown, TOPAS OPAs fail to remember their position and Dest. Position

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#172] opened 2018-04-29 18:59 UTC

**Comment by ksunden** [comment] 2018-05-22 21:13
This is true of the TOPAS-800 as well.

Note, the motor positions themselves are fine, and setting works properly, just where it thinks it is is off

**Comment by darienmorrow** [comment] 2018-10-01 14:33
This is still an issue. Interestingly, the "motor position" as displayed by PyCMDS is `12345.679 wn` which is the minimum of the SHS tuning range I currently have loaded.

**Comment by ksunden** [comment] 2018-10-01 16:10
https://github.com/wright-group/PyCMDS/blob/adfcc08586402a6ab2d50573e5b2c432f6ffec3c/hardware/opas/TOPAS/TOPAS.py#L491

This commented out line may have something to do with it

**Comment by ksunden** [comment] 2018-10-08 22:00
Duplicate of #122, closing that one as this one has more information

**Comment by ksunden** [comment] 2019-04-10 16:00
One note that came up accidentally recently:

The value that it usually ends up as on the PS table is 1666.666 wn (6000 nm).

However, on one particular startup where the monochromator failed to initialize, and therefore the whole startup was halted (that's a different problem, but hey, one at a time) the value displayed as 2200 wn, which may well have been where it was last, so something seems to be overwriting the field _after_ it is populated with a (potentially) correct value. 

I have not carefully reproduced this to confirm that it is indeed the _correct_ value, but it was interesting to note that the value was different.

**Comment by ksunden** [comment] 2019-04-10 21:59
I found the number it gets set to in "TOPAS.ini", good lead on why it gets set improperly

**Closed** 2019-04-15 13:45 UTC
Labels: Priority: High, Requires Hardware, bug
