### ISSUE TITLE
Queue problems

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#146] opened 2017-11-18 16:15 UTC
I have been experiencing some general problems with the queue. Below are some things I have noticed and experienced. Sadly, I have not been paying close attention so the details may be off;
I will attempt to provide more concrete details when I come across them. 

1. `.aqn` files and folder numbering don't update if I change the ordering in the queue.
2.  When you change the ordering or remove an acquisition, and then replace it with a different acquisition, if you "load" the new acquisition, it will actually load the old one. 
3. I attach a `.zip` file in which the `.aqn` file says that 5000 shots are supposed to be used, but the `.data` file says 100 shots were used. [Archive.zip](https://github.com/wright-group/PyCMDS/files/1484735/Archive.zip)
4. Early this morning I did a dummy scan and the scan never "finished" even though the .png got created and uploaded. This is the [queue](https://drive.google.com/drive/u/2/folders/189sWyBX_b4HUGYWh5rGY-jZiPH0ZZNeo).

**Comment by untzag** [comment] 2017-11-19 22:01
@darienmorrow can you break these into individual issues please?

which problems, if any, are preventing experiments?

number 3 seems very severe. is this issue recording to the .data file, or did the scan actually run with 100 shots? was this scan done through 'loading' or directly?

**Comment by darienmorrow** [comment] 2017-11-22 14:35
I have opened issue #148 concerning number 3 on the list.

**Comment by ksunden** [comment] 2018-10-10 03:36
number 4 is the same issue as #183, I can tell that scan 13 was deleted, causing scan 14 to be inserted into the queue twice, thus the first one that ran was actually the second intended to run, and it uploaded in the previous case, but never uploaded 013

**Comment by ksunden** [comment] 2018-10-10 03:38
Actually, the same goes for number 2 as well

**Comment by ksunden** [comment] 2018-10-10 03:41
I intend to make 1 PR to close this and #183 (seeing that the one issue raised here that is not caused by the same root is already spun off into it's own issue)

**Closed** 2018-10-25 15:48 UTC
Labels: Priority: High, bug
