### ISSUE TITLE
Constants feature in PyCMDS seems to depend on display units.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#84] opened 2017-02-25 21:19 UTC
While using `constants` to set the monochromator along when moving OPAs. The feature only seems to work as intended when the display units on the LHS of the PyCMDS window are all the same units.

**Comment by untzag** [comment] 2017-02-25 23:00
Duplicate of #58.

Closing in favor of older issue.

**Closed by untzag** 2017-02-25 23:00 UTC
Labels: duplicate
